version: '3'

services:
  app:
    image: 'cardatabase'
    build:
      context: .
    container_name: cardatabase
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=password'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'

  postgres:
    image: 'postgres:alpine'
    container_name: 'postgres-cardatabase'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=postgres'

