spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: password
    hikari:
      schema: cardatabase
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        security: TRACE

okta:
  oauth2:
    issuer: ---
    audience: ---
