spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: password
    hikari:
      schema: cardatabase
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: dev-sck8h0bo4a4lx2rq.us.auth0.com
logging:
  level:
    org:
      springframework:
        security: TRACE
server:
  port: '8080'
auth0:
  audience: 'https://cardatabase/api'
  domain: dev-sck8h0bo4a4lx2rq.us.auth0.com